version: '3'

services:

  mylaravel:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mylaravel
    container_name: mylaravel
    environment:
      - PORT=80
      # - TZ=${WORKSPACE_TIMEZONE}
    # volumes:
    #   - ${DATABASE_PATH}/mysql:/var/lib/mysql
    # privileged: true
    ports:
      - "80:80"
    depends_on:
      - mysql
  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mylaravel
      - MYSQL_ROOT_PASSWORD=root